### ISSUE TITLE
Disable inactive users automatically via API

### ISSUE THREAD

**Issue by hutchenlooker** [deangelo-llooker/gzr#1]
As far as I can see, we are very close to being able to do this via i_looker + `update_user` API, but the problem is the i_looker explore on `event` gives you all logins per user, not just the max or last one. I've filed a request for custom fields to allow Max() on Date fields to get around this. But this would be a great addition to gzr.

**Comment by deangelo-llooker** [comment]
I added the `--last-login` switch to `gzr user ls` to display the most recent login by any interactive method. This command will allow you to retrieve the last logins for every user.

```
# only show users with a non-blank last login, sorted in reverse (oldest at bottom)
gzr user ls --host=looker.example.com --fields=id,email --last-login --plain | grep -v "^ " | sort -r
```

Once you identify the users you want to from this list, you can use the new `gzr user disable` command to disable the user.

For automation, you can use any of a bunch of scripting tools. For example using `gawk` to filter the date range. 

```
# on mac you may need to install gawk with homebrew: $ brew install gawk
# Most Linux installations should have it by default

gzr user ls --host=looker.example.com --fields=id,email --last-login --plain | gawk -f filter_dates.awk  -v starttime='1970 00 00 00 00 00' -v endtime='2015 01 01 0 00 00'
```

The filter_dates.awk script is...
```awk
BEGIN {
    starttime = mktime(starttime)
    endtime = mktime(endtime)
}

func in_range(n, start, end) {
    return start <= n && n < end
}

match($0, /^([0-9]{4})-([0-9]{2})-([0-9]{2})\s/, m) &&
    in_range(mktime(m[1] " " m[2] " " m[3] " 00 00 00"), starttime, endtime)
```

Putting these bits together, we can do something like this to disable all those users.

```
gzr user ls --host=looker.example.com --fields=id,email --last-login --plain | \
  gawk -f filter_dates.awk  -v starttime='1970 00 00 00 00 00' -v endtime='2015 01 01 0 00 00' | \
  cut -c27-31 | xargs -n 1 gzr user --host=looker.example.com disable
```

Easy!
