### ISSUE TITLE
Schedule run once: Not found

### ISSUE THREAD

**Issue by pioneer903** [deangelo-llooker/gzr#16]
## Expected behavior
When executing a command to run schedule once, gazer should run the schedule and deliver content to specified destination

## Actual behavior
Getting error: Not found
JSON file of the schedule is provided in the stdout.
When I grab the JSON and run it in Looker API, i get the same error. I discovered that if i remove 'id' from the JSON, the schedule runs fine in Looker API
 
## Steps to reproduce the behavior
`gzr plan runit 843 --host=looker.company.com --no-verify-ssl`

Please let me know if i can provide any additional information.

Thank you

**Comment by deangelo-llooker** [comment]
fixed in https://github.com/deangelo-llooker/gzr/commit/2e9dbe505ba232031f7712c3da43809e27669bca

Part of release 0.2.9
