### ISSUE TITLE
Distinguish "Invalid Credentials" error message from "SSL problem"

### ISSUE THREAD

**Issue by ajcrutch** [deangelo-llooker/gzr#8]
I was trying to authenticate into gazer and kept getting an "Invalid Credentials" error message even though they were correct.  The problem turned out to be solved when I used the option to not check for proper SSL (temporary workaround, actually fixing the problem now).  If there was a different message I could have saved some time.  Thanks!

**Comment by ryandunlavy** [comment]
+1 me

**Comment by deangelo-llooker** [comment]
Fixed
