### ISSUE TITLE
content migration forgot dashboard filter listeners

### ISSUE THREAD

**Issue by ajcrutch** [deangelo-llooker/gzr#9]
Customer reported, so I don't have any screenshots.  The report was that everything went great, but once the content was in the destination the listeners had to be set up again since they were not carried through  with the rest of the content.

Saw this issue, maybe related?  https://github.com/looker/analytics/issues/2714

**Comment by ajcrutch** [comment]
+1 Sunrun

**Comment by elanweiner** [comment]
+1 Intel

**Comment by elanweiner** [comment]
tile filters are not over ridden but global dashboard filters/listeners are

**Comment by ajcrutch** [comment]
@elanweiner can you elaborate what you mean?

**Comment by deangelo-llooker** [comment]
Fixed in gazer v 0.2.3.
